### PR TITLE
Remodeling

### PR DESCRIPTION
**Pull request by gatorpazz**
The plan is to make a motherfuckin website, want specifics? Check out the issues

### CODE REVIEW

**Comment by gatorpazz** [comment]
Responsiveness issue

https://github.com/gatorpazz/gatorpazz.github.io/issues/9

**Comment by gatorpazz** [comment]
Navigation Bar

https://github.com/gatorpazz/gatorpazz.github.io/issues/10

**Comment by gatorpazz** [comment]
Blog Post Issue

https://github.com/gatorpazz/gatorpazz.github.io/issues/11

**Comment by gatorpazz** [comment]
Footer and Comments

https://github.com/gatorpazz/gatorpazz.github.io/issues/12

**Comment by gatorpazz** [comment]
Demo site: http://wrapbootstrap.com/preview/WB04133G7

**Comment by al-the-x** [comment]
_No description provided_...? Where's dat plan, son?

**Comment by al-the-x** [comment]
You have way more features than this in your template, per our in-class discussion... dissection... whatever.

**Comment by al-the-x** [comment]
Those marked-up screenshots should live in `specs/`, not `img/`... The latter is usually reserved for images that contribute to they layout of the page. Putting them in `specs/` identifies them  as a group.

**Pull request merged**
